package com.ifpb.agendaeletronica.interfacegrafica;

import com.ifpb.agendaeletronica.cadastro.AgendaDaoBanco;
import com.ifpb.agendaeletronica.cadastro.AgendaDaoBinario;
import com.ifpb.agendaeletronica.cadastro.CompromissoDaoBanco;
import com.ifpb.agendaeletronica.cadastro.CompromissoDaoBinario;
import com.ifpb.agendaeletronica.cadastro.UsuarioDaoBanco;
import com.ifpb.agendaeletronica.cadastro.UsuarioDaoBinario;
import com.ifpb.agendaeletronica.entidades.Agenda;
import com.ifpb.agendaeletronica.entidades.Compromisso;
import com.ifpb.agendaeletronica.entidades.Usuario;
import com.ifpb.agendaeletronica.excecoes.DescricaoInvalidaException;
import com.ifpb.agendaeletronica.excecoes.LocalInvalidoException;
import com.ifpb.agendaeletronica.excecoes.NomeInvalidoException;
import com.ifpb.agendaeletronica.interfaces.AgendaDao;
import com.ifpb.agendaeletronica.interfaces.CompromissoDao;
import com.ifpb.agendaeletronica.interfaces.UsuarioDao;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.DateTimeException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Familia
 */
public class TelaCompromisso extends javax.swing.JFrame {

    /**
     * Creates new form TelaCompromisso
     */
     private AgendaDao dao;
     private UsuarioDao dao2;
     private CompromissoDao dao3;
    public TelaCompromisso() {

        dao = new AgendaDaoBinario();
        dao2= new UsuarioDaoBinario();
        dao3 = new CompromissoDaoBinario();
        initComponents();
          inicializarComponentes();
    }
 public void inicializarComponentes(){
         List<String> listaNomesAgendas = new ArrayList<>();
         
         try {
             listaNomesAgendas = dao.retornaNomeAgendas();
         } catch (IOException | ClassNotFoundException ex) {
              JOptionPane.showMessageDialog(null,
                    "Falha na Conexão",
                    "Mensagem de Erro",
                    JOptionPane.ERROR_MESSAGE);
         }catch(SQLException ex){
             JOptionPane.showMessageDialog(null,
                    "já exite uma agenda com esse nome",
                    "Mensagem de Erro",
                    JOptionPane.ERROR_MESSAGE);
         }
        comboAgenda.removeAllItems(); 
        for(int i = 0; i<listaNomesAgendas.size(); i++)
        comboAgenda.addItem(listaNomesAgendas.get(i));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoData = new com.toedter.calendar.JDateChooser();
        campoHora = new javax.swing.JSpinner();
        campoMinuto = new javax.swing.JSpinner();
        campoDescricao = new javax.swing.JTextField();
        campoLocal = new javax.swing.JTextField();
        comboAgenda = new javax.swing.JComboBox();
        botaoOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Novo Compromisso");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Data");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Hora");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Descrição");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Local");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Agenda");

        campoData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        campoHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoHora.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        campoMinuto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoMinuto.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        campoDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDescricaoActionPerformed(evt);
            }
        });

        campoLocal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLocalActionPerformed(evt);
            }
        });

        comboAgenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAgendaActionPerformed(evt);
            }
        });

        botaoOk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoOk.setText("OK");
        botaoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoDescricao)
                                    .addComponent(campoLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(comboAgenda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(botaoOk)))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoHora, campoMinuto});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(botaoOk)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDescricaoActionPerformed

    private void campoLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLocalActionPerformed

    private void botaoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOkActionPerformed
    
        Compromisso compromisso = new Compromisso();
       
        try {

            compromisso.setDescricao(campoDescricao.getText());

            compromisso.setLocal(campoLocal.getText());
            
            LocalDate data = LocalDate.parse(new SimpleDateFormat("yyyy-MM-dd").format(campoData.getDate()));
           
            compromisso.setData(data);

            int hour = (int) campoHora.getValue();
            int minute = (int) campoMinuto.getValue();
           
           LocalTime hora = LocalTime.of(hour, minute);
           compromisso.setHora(hora);
            
           compromisso.setEmail(TelaInicial.usuarioLogado.getEmail());
           compromisso.setNome((String) comboAgenda.getSelectedItem());

                if (dao3.createCompromisso(compromisso)){
                    System.out.println(dao3.updateCompromisso(compromisso));
                    JOptionPane.showMessageDialog(null,
                            "Compromisso Adicionado Com Sucesso");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Compromisso Não Pode Ser Adicionado",
                            "Mensagem de Erro",
                            JOptionPane.ERROR_MESSAGE);
                }
             

        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(null,
                    "Data Inválida", "Mensagem de Erro",
                    JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null,
                    "Data Inválida", "Mensagem de Erro",
                    JOptionPane.ERROR_MESSAGE);
        }catch (IOException | ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(null,
                    "Falha na Conexão",
                    "Mensagem de Erro",
                    JOptionPane.ERROR_MESSAGE);
        }catch(DateTimeException ex){
            JOptionPane.showMessageDialog(null,
                    "Data ou Hora Inválida", "Mensagem de Erro",
                    JOptionPane.ERROR_MESSAGE);
        }catch(DescricaoInvalidaException ex) {
            JOptionPane.showMessageDialog(null,
                    "A Descrição Não Pode Ser Vazia", "Mensagem de Erro",
                    JOptionPane.ERROR_MESSAGE);
        }catch(LocalInvalidoException ex){
           JOptionPane.showMessageDialog(null,
                    "O Local Não Pode Ser Vazio", "Mensagem de Erro",
                    JOptionPane.ERROR_MESSAGE); 
        }catch(SQLException ex){
             JOptionPane.showMessageDialog(null,
                    "já exite uma agenda com esse nome",
                    "Mensagem de Erro",
                    JOptionPane.ERROR_MESSAGE);
         }catch(NomeInvalidoException ex){
            JOptionPane.showMessageDialog(null,
                    "Agenda Não pode ser Vazia");
         }     
    }//GEN-LAST:event_botaoOkActionPerformed

    private void comboAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAgendaActionPerformed
    
   
    }//GEN-LAST:event_comboAgendaActionPerformed

    /**
     * @param args the command line arguments
     */
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCompromisso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCompromisso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCompromisso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCompromisso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCompromisso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoOk;
    private com.toedter.calendar.JDateChooser campoData;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JSpinner campoHora;
    private javax.swing.JTextField campoLocal;
    private javax.swing.JSpinner campoMinuto;
    private javax.swing.JComboBox comboAgenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
